package org.lasarobotics.hazybot.inputs;

import org.json.simple.JSONObject;
import org.lasarobotics.hazybot.ConfigException;

/**
 * Output that throws away value, used to avoid crashing program
 * if a valid Output cannot be generated by a config
 */
public class ConstInput extends Input {
    private double value;

    public void config(JSONObject config) throws ConfigException {
        value = (double) config.get("value");
    }

    public double getInput() {
        return value;
    }
}
