package org.lasarobotics.hazybot.inputs;

import org.json.simple.JSONObject;
import org.lasarobotics.hazybot.ConfigException;

/**
 * Output that throws away value, used to avoid crashing program
 * if a valid Output cannot be generated by a config
 */
public class ConstInput<I> extends Input<I> {
    private I value;

    public void config(JSONObject config) throws ConfigException {
        I value = (I) config.get("value");
    }

    public I getInput() {
        return value;
    }
}
