package org.lasarobotics.hazybot.outputs;

import org.json.simple.JSONObject;
import org.lasarobotics.hazybot.ConfigException;

/**
 * Output that throws away value, used to avoid crashing program
 * if a valid Output cannot be generated by a config
 */
public class NullOutput extends Output {
    public void config(JSONObject config) throws ConfigException {
    }

    public void setOutput(Object value) {
    }
}
